---
brew_taps:
  - domt4/autoupdate
  - homebrew/cask-versions
  - homebrew/cask-fonts

brew_packages:
  - git
  - git-extras
  - ansible
  - terminal-notifier     # used inside this repo
  - neovim
  - asciinema
  - bitwarden-cli
  - coreutils
  - exa                   # modern ls
  - ripgrep               # modern grep
  - bat                   # modern cat
  - ffmpeg
  - gpg2
  - btop
  - imapsync
  - iperf
  - mas                   # mac store command line interface
  - nmap
  - tmux
  - node
  - wget
  - zplug
  - zsh
  - cowsay                # funny terminal stuff
  - neofetch              # informations about the system
  - stow                  # must for syslink files
  - duti                  # setup defaults from cmd line
  - syncthing
  - openjdk
  - postgresql
  - speedtest-cli
  - tree
  - obsidian

cask_packages:
  - github
  - brave-browser
  - aerial
  - raycast               # alfred alternative
  - arc                   # browser
  - appcleaner
  - discord
  - docker
  - dropbox
  - font-hack-nerd-font
  - google-chrome
  - iterm2
  - qlstephen
  - quicklook-json
  - spotify
  - suspicious-package
  - telegram
  - visual-studio-code
  - iina
  - karabiner-elements
  - expressions
  - insomnia                # postman alternative opensource
  - zoom
  - gimp
  - inkscape
  - blackhole-2ch           # virtual audio cable
  - cakebrew
  - notesnook
  - the-unarchiver
  - microsoft-office
  - whatsapp
  - ngrok
  - figma
  - microsoft-teams
  - obs
  - reflector
  - rectangle
  - syncthing       # parte visuale
  - font-fira-code
  - font-poppins
  - authy
  - ghidra
  - openinterminal  # shortcut for finder
  - raspberry-pi-imager
  - localsend
  # - vlc
  # - postman

# gem_packages:
  # - nokogiri

mas_packages:
  - 1451685025    # Wireguard
  - 409183694     # Keynote
  - 1452453066    # HiddenBar
  - 571213070     # Da Vinci Resolve
  - 1284863847    # unsplash wallpaper
  - 937984704     # amphetamine
  
  # - 1295203466    # Microsoft Remote Desktop
  # - 1289583905  # Pixelmator Pro
  # - 408981434     # iMovie
  # - 430255202     # Mactracker

npm_packages:
  # - bower
  # - giracli
  # - grunt
  # - gulp
  # - init.js
  # - json
  # - prettyjson
  # - tlstools
  # - yarn
  # - yo
  - nodemon

pip_packages:
  - beautifulsoup4
  - docker
  - ffpb
  - patool
