- name: "[dotfiles] Get list of files to symlink"
  shell: "ls -1 ~/.dotfiles/files/dotfiles  > /tmp/dotfiles_symlinks_to_build"

- name: "[dotfiles] Store list of files into variable"
  shell: "cat /tmp/dotfiles_symlinks_to_build"
  register: filesToSymlink

- name: "[dotfiles] Set symlinks"
  file:
    src: '{{ ansible_env.PWD }}/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  with_items:
    - "{{filesToSymlink.stdout_lines}}"

- name: "[dotfiles] Download Vundle (vi bundle manager)"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: "[dotfiles] Setup and install Vundle"
  shell:
    cmd: echo | echo | vim +PluginInstall +qall &>/dev/null
