brew_taps:
  - frdmn/formulas
  - homebrew/cask-versions

brew_packages:
  - ansible
  - asciinema
  - bats
  - coreutils
  - ddig
  - dev-search
  - exiftool
  - git-extras
  - go
  - imapsync
  - iperf
  - java
  - jq
  - mas
  - media-info
  - mitmproxy
  - mtr
  - nmap
  - nodejs
  - odig
  - terminal-notifier
  - tmux
  - uping
  - wakeonlan
  - youtube-dl
  - zplug
  - zsh

cask_packages:
  - 1password
  - aerial
  - alfred
  - appcleaner
  - atext
  - bartender
  - carbon-copy-cloner
  - discord
  - docker
  - dropbox
  - gas-mask
  - gitup
  - google-chrome
  - hex-fiend
  - iterm2
  - keka
  - macdown
  - nordvpn
  - nvalt
  - spotify
  - things
  - telegram
  - textual
  - transmit
  - vagrant
  - virtualbox
  - visual-studio-code-insiders
  - vlc
  - wireshark

cask_ql_packages:
  - provisionql
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-csv
  - quicklook-json
  - suspicious-package
  - webpquicklook